// Project sayfasında gösterilen kod örneği
export const projectsCodeSample = [
  `// Tokyo Night Temalı Projeler Bileşeni`,
  `const Projects = () => {`,
  `  const [showAll, setShowAll] = useState(false);`,
  `  const projects = [`,
  `    {`,
  `      title: "KesifPlus",`,
  `      description: "AI-powered education platform",`,
  `      features: ["React", "TypeScript", "AI-Enhanced"],`,
  `      status: "development"`,
  `    },`,
  `    {`,
  `      title: "Live Code Editor",`,
  `      description: "Real-time HTML & CSS preview editor",`,
  `      features: ["Live Preview", "Code Editor", "Syntax Highlighting"],`,
  `      status: "development"`,
  `    },`,
  `    {`,
  `      title: "Mindbook",`,
  `      description: "AI-enhanced React Native note-taking app",`,
  `      features: ["React Native", "Dark Mode", "AI-Enhanced"],`,
  `      status: "private"`,
  `    },`,
  `    {`,
  `      title: "Raspberry Pi WiFi Extender",`,
  `      description: "AI-optimized WiFi extender tool",`,
  `      features: ["Python", "Network Management", "AI-Enhanced"],`,
  `      githubLink: "https://github.com/melihcanndemir/raspberrypi_wifi_extender"`,
  `    },`,
  `    {`,
  `      title: "React Project Automator",`,
  `      description: "AI-powered React project creation tool",`,
  `      features: ["Cross-Platform", "Git Integration", "AI-Enhanced"],`,
  `      githubLink: "https://github.com/melihcanndemir/React-Project-Automator"`,
  `    },`,
  `    {`,
  `      title: "QR Code Scanner",`,
  `      description: "AI-enhanced QR code scanning app",`,
  `      features: ["QR Scanning", "QR Generation", "AI-Enhanced"],`,
  `      status: "development"`,
  `    },`,
  `    {`,
  `      title: "APK Backup",`,
  `      description: "AI-optimized Android app backup tool",`,
  `      features: ["Android", "Cloud Storage", "AI-Enhanced"],`,
  `      playStoreLink: "https://play.google.com/store/apps/details?id=com.melihcandemir.apkbackup",`,
  `      popular: true`,
  `    },`,
  `    {`,
  `      title: "Notepad",`,
  `      description: "AI-enhanced modern note-taking app",`,
  `      features: ["Android", "Notes", "AI-Enhanced"],`,
  `      playStoreLink: "https://play.google.com/store/apps/details?id=com.melihcandemir.notepad",`,
  `      popular: true`,
  `    },`,
  `    {`,
  `      title: "CodeLLAMA Chat",`,
  `      description: "AI code assistant using LLAMA 7B model",`,
  `      features: ["LLAMA 7B", "Code Completion", "AI-Enhanced"],`,
  `      githubLink: "https://github.com/melihcanndemir/code_llama_ai",`,
  `      popular: true`,
  `    },`,
  `    {`,
  `      title: "Markdown Previewer",`,
  `      description: "AI-enhanced Markdown preview tool",`,
  `      features: ["Markdown", "Live Preview", "AI-Enhanced"],`,
  `      liveLink: "https://webmarkdown.netlify.app/",`,
  `      githubLink: "https://github.com/melihcanndemir/markdown-previewer",`,
  `      popular: true`,
  `    },`,
  `    {`,
  `      title: "UUID & HEX Generator",`,
  `      description: "AI-optimized UUID and HEX color code generator",`,
  `      features: ["UUID", "HEX Colors", "AI-Enhanced"],`,
  `      liveLink: "https://uuid-hex-generator.netlify.app/",`,
  `      githubLink: "https://github.com/melihcanndemir/uuid-hex-generator",`,
  `      popular: true`,
  `    }`,
  `  ];`,
  ``,
  `  return (`,
  `    <section className="py-20 px-6 bg-[#1a1b26] text-white">`,
  `      <h2 className="text-4xl font-bold text-[#7aa2f7]">Projects</h2>`,
  `      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">`,
  `        {projects.map(project => (`,
  `          <div className="p-6 bg-gradient-to-br from-[#24283b] via-[#2a2e3f] to-[#1a1b26] rounded-lg shadow-lg hover:shadow-xl border border-[#414868] transition-all duration-300 hover:bg-gradient-to-br hover:from-[#2a2e3f] hover:via-[#24283b] hover:to-[#1f2335]">`,
  `            <h3>{project.title}</h3>`,
  `            <p>{project.description}</p>`,
  `            {/* ... diğer proje detayları ... */}`,
  `          </div>`,
  `        ))}`,
  `      </div>`,
  `    </section>`,
  `  );`,
  `};`
]; 